Repository SSathu/Magma-soen341project2023, pull requests merged in 2023-02, with the labels that each got.

#4 Creating sprint 3 folder and README
  Sprint 3/README.md
Labels: question

#6 Update README.md
  Sprint 4/README.md
Labels: invalid

#7 Update README.md
  README.md
Labels: good first issue

#14 Update README.md
  README.md
Labels: documentation
